# Generated by Django 5.1.3 on 2024-11-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('full_carwash', 'Full Carwash - 70 Rupees'), ('inside_vacuum', 'Inside Vacuum - 40 Rupees'), ('only_body', 'Only Body - 30 Rupees'), ('full_with_polish', 'Full with Polish - 100 Rupees'), ('only_polish', 'Only Polish - 30 Rupees')], default='full_carwash', max_length=50)),
                ('service_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
