# Generated by Django 5.1.3 on 2024-11-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_carwashservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesmodel',
            old_name='Employee_name',
            new_name='employee_name',
        ),
    ]
