# Generated by Django 5.1.3 on 2024-11-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_employee_name_employeesmodel_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='employee',
        ),
    ]
