# Generated by Django 5.1.3 on 2024-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_customer_employee_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashservice',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='carwashservice',
            name='service_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='carwashservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Complete'), ('in_progress', 'In Progress')], default='pending', max_length=15),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
