# Generated by Django 5.1.3 on 2024-11-29 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_carwashservice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashservice',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarWashService', to=settings.AUTH_USER_MODEL),
        ),
    ]
