# Generated by Django 5.1.3 on 2024-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_outstandingtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='OutstandingToken',
        ),
    ]
