# Generated by Django 5.1.3 on 2024-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_reviewmodel_delete_outstandingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='free_services_used',
            field=models.IntegerField(default=0),
        ),
    ]
